
IndexError: list index out of range	
# индекс списка вышел за пределы диапазона

TypeError: 'list' object is not callable
# Ответ: print=

TypeError: can only concatenate list (not "int") to list
# Нельзя - объединять список с числом digs2 = digs2 +7

TypeError: '>' not supported between instances of 'int' and 'str'
# Нельзя - число сравнивать с строкой

ValueError: list.remove(x): x not in list
# Метод .remove(True) - нет элемента по значению к удалению22:36 08.06.2021 

Traceback (most recent call last): File "<pyshell#5>", line 1, in <module> A[100] KeyError: 100
# Словарь - коллекция по ключу - неправильный ключ

NameError: name 'd' is not defined
# Словарь - коллекция по ключу - неправильная переменная в которой хранится ключ и значение

TypeError: unhashable type: 'list'
# Словарь - если мы укажем изменяемый тип в качестве ключа 

KeyError: 'popitem(): dictionary is empty'
# Если словарь пуст, то возникает ошибка

ValueError: too many values to unpack (expected 2)
# В кортеже 2 переменные, 3 значения

TypeError: 'tuple' object does not support item assignment
# кортеж - Не можем определенному значению присвоить другое значение

TypeError: 'tuple' object doesn't support item deletion
# кортеж - не можем удалять отдельные элементы из кортежа

ValueError: tuple.index(x): x not in tuple
# кортеж - error - нет элемента в кортеже

none
#  return x - функция возвращает

TypeError: getSquare() takes 2 positional arguments but 3 were given 
# функция def - 3 аргумента, должно быть два

TypeError: getSquare() missing 1 required positional argument: 'h'
# функция def - 1 аргумент, должен быть один

TypeError: theySayHello() missing 1 required positional argument: 'msg1'
# функция def - переопределение функции, аргумент обязательно нужно указывать
# функция def - переопределение функции, может и ненадо в глобальной переменной True , False